AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template for creating a EC2 instance and installing Dynatrace ActiveGate 
Parameters:
 DynatraceTenant:
  Type: String
  Description: Enter the Dynatrace Tenant URL. It should be of the form "https://tenantUID.live.dynatrace.com"
 DynatraceInstallerToken:
  Type: String
  Description: Get the installer Token from Dynatrace ActiveGate installer URL 
Resources:
 EC2InstanceDynatraceAG:
  Type: AWS::EC2::Instance
  Properties:
   AvailabilityZone: us-east-1a
   ImageId: ami-14c5486b
   InstanceType: t2.2xlarge
   KeyName: EastUS1
   UserData:
    Fn::Base64:
     !Sub |
      #!/bin/bash -x
      yum update -y
      yum install wget -y
      wget -O /tmp/dynatrace-activegate.sh "${DynatraceTenant}/api/v1/deployment/installer/gateway/unix/latest?Api-Token=${DynatraceInstallerToken}&arch=x86&flavor=default"
      /bin/sh /tmp/dynatrace-activegate.sh
   NetworkInterfaces:
    - AssociatePublicIpAddress: "true"
      DeviceIndex: "0"
      SubnetId: !Ref SubnetAGNode
      GroupSet:
       - !Ref AGNodeSecurityGroup
   BlockDeviceMappings: 
          - DeviceName: "/dev/xvda"
            Ebs: 
              VolumeType: "io1"
              Iops: "200"
              DeleteOnTermination: "false"
              VolumeSize: "100"
 VPCActiveGateNode:
  Type: AWS::EC2::VPC
  Properties:
   CidrBlock: 10.0.0.0/28
   EnableDnsHostnames: true
   EnableDnsSupport: true
   InstanceTenancy: default
 InternetGateway:
  Type: AWS::EC2::InternetGateway
 VPCGatewayAttachment:
  Type: AWS::EC2::VPCGatewayAttachment
  Properties:
   VpcId: !Ref VPCActiveGateNode
   InternetGatewayId: !Ref InternetGateway
 SubnetAGNode:
  Type: AWS::EC2::Subnet
  Properties:
   AvailabilityZone: us-east-1a
   VpcId: !Ref VPCActiveGateNode
   CidrBlock: 10.0.0.0/28
   MapPublicIpOnLaunch: true
 RouteTable:
  Type: AWS::EC2::RouteTable
  Properties:
   VpcId: !Ref VPCActiveGateNode
 InternetRoute:
  Type: AWS::EC2::Route
  DependsOn: InternetGateway
  Properties:
   DestinationCidrBlock: 0.0.0.0/0
   GatewayId: !Ref InternetGateway
   RouteTableId: !Ref RouteTable
 SubnetAGNodeRouteTableAssociation:
  Type: AWS::EC2::SubnetRouteTableAssociation
  Properties:
   RouteTableId: !Ref RouteTable
   SubnetId: !Ref SubnetAGNode
 AGNodeSecurityGroup:
  Type: AWS::EC2::SecurityGroup
  Properties:
   GroupDescription: "Enable HTTP Access via port 80, and open all the other ports for Managed install"
   VpcId: !Ref VPCActiveGateNode
   SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: '9999'
        IpProtocol: tcp
        ToPort: '9999'
      - CidrIp: 0.0.0.0/0
        FromPort: '22'
        IpProtocol: tcp
        ToPort: '22'
      - CidrIp: 0.0.0.0/0
        FromPort: '443'
        IpProtocol: tcp
        ToPort: '443'
      - CidrIp: 0.0.0.0/0
        FromPort: '8443'
        IpProtocol: tcp
        ToPort: '8443'
   SecurityGroupEgress:
      - CidrIp: 0.0.0.0/0
        FromPort: '443'
        IpProtocol: tcp
        ToPort: '443'
      - CidrIp: 0.0.0.0/0
        FromPort: '8443'
        ToPort: '8443'
        IpProtocol: tcp
      - CidrIp: 0.0.0.0/0
        FromPort: '9999'
        ToPort: '9999'
        IpProtocol: tcp
